package com.lzc.exovideo.downloader.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lzc.exovideo.db.entity.UnAbleFilm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UN_ABLE_FILM".
*/
public class UnAbleFilmDao extends AbstractDao<UnAbleFilm, Long> {

    public static final String TABLENAME = "UN_ABLE_FILM";

    /**
     * Properties of entity UnAbleFilm.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property LinkUrl = new Property(1, String.class, "linkUrl", false, "LINK_URL");
        public final static Property FileName = new Property(2, String.class, "fileName", false, "FILE_NAME");
    }


    public UnAbleFilmDao(DaoConfig config) {
        super(config);
    }
    
    public UnAbleFilmDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UN_ABLE_FILM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"LINK_URL\" TEXT," + // 1: linkUrl
                "\"FILE_NAME\" TEXT);"); // 2: fileName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UN_ABLE_FILM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UnAbleFilm entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String linkUrl = entity.getLinkUrl();
        if (linkUrl != null) {
            stmt.bindString(2, linkUrl);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(3, fileName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UnAbleFilm entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String linkUrl = entity.getLinkUrl();
        if (linkUrl != null) {
            stmt.bindString(2, linkUrl);
        }
 
        String fileName = entity.getFileName();
        if (fileName != null) {
            stmt.bindString(3, fileName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UnAbleFilm readEntity(Cursor cursor, int offset) {
        UnAbleFilm entity = new UnAbleFilm( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // linkUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // fileName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UnAbleFilm entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLinkUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFileName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UnAbleFilm entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UnAbleFilm entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UnAbleFilm entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
